version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3306"    # maps host port 3307 to container port 3306
    environment:
      MYSQL_DATABASE: satisactual_1
      MYSQL_USER: ram
      MYSQL_PASSWORD: its
      MYSQL_ROOT_PASSWORD: its
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - project-network

  web:
    build: .
    container_name: django_app
    command: /app/entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: satisactual_1
      DB_USER: ram
      DB_PASSWORD: its
    networks:
      - project-network

volumes:
  db_data:

networks:
  project-network: