version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: satisactual_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""                # empty password
      MYSQL_DATABASE: satisactual_1
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: satisactual_web
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=satisactual_new
      - DB_USER=root
      - DB_PASSWORD=  # empty

volumes:
  db_data:
